#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	
	if [ "systemd" == "$INITSYS" ]; then
		ln -s /usr/lib/zdesk/zdesk /usr/bin/zdesk

		if [ -e /etc/systemd/system/zdesk.service ]; then
			rm /etc/systemd/system/zdesk.service /usr/lib/systemd/system/zdesk.service /usr/lib/systemd/user/zdesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/zdesk/files/systemd/zdesk.service /usr/lib/systemd/system/zdesk.service
		systemctl daemon-reload
		systemctl enable zdesk
		systemctl start zdesk
	fi
fi
